module Main where

-- custom-build-tool
import CustomBuildTool
  ( mkCustomBuildTool )

-- package-with-hooks
import Paths_package_with_hooks -- (Cabal autogenerated module)
  ( getDataFileName )

--------------------------------------------------------------------------------

main :: IO ()
main = do
  customDataFile <- getDataFileName "CustomPP2Data.txt"
  mkCustomBuildTool "custom-pp2" customDataFile
