module Main where

-- custom-build-tool
import CustomBuildTool
  ( mkCustomBuildTool )
import Paths_custom_build_tool -- (Cabal autogenerated module)
  ( getDataFileName )

--------------------------------------------------------------------------------

main :: IO ()
main = do
  customDataFile <- getDataFileName "CustomPP1Data.txt"
  mkCustomBuildTool "custom-pp1" customDataFile
